Makefile

Create directories in Makefile so that "make html" works on a new fork.

Create directories needed for the HTML version

---

src/exercises/ez-8-1.xml
src/exercises/ez-8-2.xml
src/exercises/ez-8-3.xml

This is not practice.  Ready to go.  I have some general comments about titling, but they really do not belong here.
I'll do the second half of this chapter if necessary.

Add titles to WeBWorK exercises about sequences and series

---

src/exercises/ez-3-1.xml
src/exercises/ez-3-2.xml
src/exercises/ez-3-4.xml
src/exercises/ez-3-5.xml

This is ready to go as far as I'm concerned.

WeBWorK Exercise Titles for Chapter 3

---

src/exercises/ez-5-1.xml
src/exercises/ez-5-2.xml
src/exercises/ez-5-4.xml

Chap 5 ww titles

---

src/exercises/ez-5-2.xml
src/exercises/ez-5-3.xml
src/exercises/ez-5-5.xml
src/exercises/ez-5-6.xml

Finished titles on Chapter 5 WW.

done adding titles to Ch 5

---

src/exercises/ez-7-1.xml
src/exercises/ez-7-2.xml
src/exercises/ez-7-3.xml
src/exercises/ez-7-4.xml
src/exercises/ez-7-5.xml
src/exercises/ez-7-6.xml

Will do more of chapter 7 later.

WebWork titles added for 7.1-7.3

---

src/activities/act-1-1-1.xml
src/previews/PA-1-1.xml
src/sec-1-1-vel.xml

I copied Kathy's changes into a new branch, and reformatted.
We have lost the trail that these changes came from Kathy,
because that is beyond my git knowledge.
This can be treated as if it was a pull request from Kathy.

Kathy's files, prettyprinted

---

Makefile
src/acs-solution-manual.xml
xsl/acs-solution-manual.xsl

Here's the first round of code to get a solutions manual in production. I'll show and tell and have some questions on our Friday call, but this is ready to be merged as is.

Solution manual capability

---

.gitignore
src/backmatter.xml
src/bookinfo.xml
src/frontmatter.xml

Further work on pretty printing, since David's script wasn't fully handling all the top level PTX tags.

Pretty printing

---

src/activities/act-5-3-1.xml
src/activities/act-5-5-2.xml
src/activities/act-6-3-3.xml

With these fixes to the LaTeX code in solutions, the solutions manual fully compiles. I'm impressed that all of that rarely if ever LaTeX in the solutions only had three mistakes in it!

Fix LaTeX errors in solutions

---

src/acs-activity-workbook.xml
src/colophon.xml
src/frontmatter.xml
src/titlepage.xml
xsl/acs-latex.xsl

This allows titlepage and colophon can be recycled in solution manual and activity workbook

Modularize frontmatter

---

README.md

Avoid the problem in issue #101 (which has already been closed)

Add WW extraction step to README

---

src/sec-1-2-lim.xml

Here are some edits of section 1.2.  I'll send more in an e-mail.

edited section1.2

---

src/sec-1-3-derivative-pt.xml

Some suggestions for Section 1.3.
In particular, in a few places you refer to "units of f."  I would change this to "units of f(x)," because f is the name of a function, not a variable.  (It is a common practice to conflate the name of the function with the name of the independent variable, but in that case the function usually takes on the name of the variable.)  If you prefer "units of f," it would be a good idea to point out that you are using f for the independent variable as well as the function (but I think that would be more confusing!)

edits to sec1.3

---

src/sec-1-4-derivative-fxn.xml

Suggestions for Section 1.4.
Note that in the Summary you use the term "differentiable," but this has not been defined in the section.  I suggest that you insert a comment earlier, because students sometimes are not aware that the words "derivative" and "differentiable" refer to the same operation.

suggestions for Sec 1.4.

---

src/sec-1-6-second-d.xml

suggestions for section 1.6

---

src/sec-1-7-lim-cont-diff.xml

suggestions for section 1.7

---

src/sec-2-1-elem-rules.xml

I would put the comment in lines 307-314 earlier, before the first use of the term "differentiable" or "differentiate."  (Was it in Chapter 1?)

suggestions for section 2.1

---

src/sec-2-2-sin-cos.xml

suggestions for section 2.2

---

src/sec-2-4-other-trig.xml

suggestions for section 2.4

---

src/sec-2-5-chain.xml

I found the order of the last subsection confusing, so I have offered another rendering.  You can decide if it is clearer or not.

suggestions for section 2.5

---

src/sec-2-6-inverse.xml

Consider setting off lines 71-82 as a Definition

suggestions for section 2.6

---

src/sec-3-1-tests.xml

Do you want to format "Definitions" for local and global extrema?

suggestions for section 3.1

---

src/sec-3-2-families.xml

suggestions for section 3.2

---

src/sec-3-3-optimization.xml

suggestions for section 3.3

---

src/sec-4-1-velocity-distance.xml

suggestions for section 4.1

---

src/sec-4-3-definite-integral.xml

suggestions for section 4.3

---

src/sec-4-4-FTC.xml

suggestions for section 4.4

---

src/sec-5-1-antid-graphs.xml

1.  I deleted the example after the blockquote in "Constructing the graph of the antiderivative" because it does not illustrate the previous discussion.  (If you can find an algebraic formula for the antiderivative, why use areas to graph it?)  I wonder if the discussion of finding an antiderivative from a graph might be better placed in or after the section on numerical integration.
2.  I suggest showing the calculations used to obtain F(1) = 1.5, etc. in lines 140-142.

suggestions for section 5.1

---

src/sec-5-3-substitution.xml

suggestions for section 5.3

---

src/sec-5-6-num-int.xml

suggestions for section 5.6

---

src/sec-6-1-area.xml

suggestions for section 6.1

---

src/sec-6-3-mass.xml

suggestions for section 6.3

---

src/sec-6-4-physics.xml

suggestions for section 6.4

---

src/sec-7-1-diff-eq-intro.xml

suggestions for section 7.1

---

src/sec-7-2-qualitative.xml

suggestions for section 7.2

---

src/sec-7-4-separable.xml

suggestions for section 7.4

---

src/sec-8-1-sequences.xml

suggestions for section 8.1

---

src/sec-8-3-series.xml

suggestions for section 8.3

---

src/sec-8-4-alternating.xml

suggestions for section 8.4

---

src/sec-8-6-power-series.xml

suggestions for section 8.6

---

Makefile
src/acs-activity-workbook.xml
src/acs-solution-manual.xml
xsl/acs-activity-workbook.xsl
xsl/acs-common.xsl
xsl/acs-latex.xsl
xsl/acs-solution-manual.xsl

All behind the scenes changes. Works with PreTeXt hash `b450238bb13b16b0be289093a5f267fe20205050`.

Automate building of 2018 Updated Solutions Manual and Activities Workbooks

---

xsl/acs-activity-workbook.xsl

Made this change in the XSLT rather than manually editing the LaTeX file. Merge whenever you want.

Remove colored block from chapter titles in workbook (KDP issue)

---

Makefile
src/acs-activity-workbook-14.xml
src/acs-activity-workbook-58.xml

This can be merged without breaking anything.

Workbooks to be KDP-compliant

---

Makefile
pub/html.xml
src/exercises/ez-4-4.xml
src/frontmatter.xml
xsl/acs-common.xsl
xsl/acs-html.xsl

Here are the updates for ACS. Same comments as I made on the PR for APC.

Updates to allow buidling with July 2020 PTX

---

src/activities/act-1-1-1.xml
src/activities/act-1-1-3.xml
src/activities/act-2-7-3.xml
src/activities/act-4-3-1.xml
src/activities/act-5-3-1.xml
src/activities/act-6-1-1.xml
src/activities/act-6-1-2.xml
src/activities/act-6-3-1.xml
src/exercises/ez-5-3.xml
src/exercises/ez-7-6.xml
src/frontmatter.xml
src/previews/PA-2-6.xml
src/sec-2-3-prod-quot.xml
src/sec-2-7-implicit.xml
src/sec-2-8-LHR.xml
src/sec-3-5-rel-rates.xml
src/sec-4-1-velocity-distance.xml
src/sec-5-2-FTC2.xml
src/sec-8-4-alternating.xml

A relatively small collection of minor typo corrections, often connected to answers and solutions for exercises or activities.

S20 acs edits

---

source/activities/act-1-5-1.xml
source/activities/act-1-5-3.xml
source/activities/act-1-6-2.xml
source/exercises/ez-5-1.xml
source/exercises/ez-6-5.xml
source/sec-4-1-velocity-distance.xml
source/sec-5-5-other-opt.xml

This takes PRs from several contributors and bundles them up to merge smoothly after some source reorganization.

Combine a bunch of PRs

---

src/exercises/ez-6-5.xml

As long as the upper limit of this integral is b, the integral is proper, so it doesn't make sense to talk about it diverging.

exercise Hfn part b: upper limit should be \infty, not b

---

source/previews/PA-8a-1.xml

As we had discussed during the minicourse.

swap out exponential for logarithm in PA 8a.1.1

---

source/previews/PA-8a-4.xml

Removed single quotes around the numbers in the tabular's answers  in part c, because the table wasn't showing up with them in there.

Update PA-8a-4.xml to make table in part c show up

---

.gitignore

This is just some cleanup to help keep git tidy.

gitignore published, .pkl, and VS Code files

---

source/exercises/ez-7-5.xml

Typo fixes in brine mixing problem

---

project.ptx
publication/publication-solutions.ptx
publication/publication-workbook-14.ptx
publication/publication-workbook-58.ptx
publication/publication.ptx
source/bookinfo.xml
source/exercises/ez-2-3.xml
source/exercises/ez-2-5.xml
source/main.ptx
source/sec-2-3-prod-quot.xml

I added a proteus version and proteus exercises to Sections 2.3 and 2.5

Adding a proteus version and proteus exercises

---

source/proteus/proteus-2-3.xml
source/proteus/proteus-2-5.xml

fixing matching problems in sections 2.3 and 2.5

---

source/proteus/proteus-2-5.xml

this is per Vilma's request on the email chain!

removed feedback from proteus-composition

---

source/proteus/proteus-template.xml

As part of a small discussion about how pretext works, I made a proteus-template.xml file with extensive comments about how to author a proteus question in pretext!

proteus exercises file template w/ comments

---

source/proteus/proteus-1-4.xml
source/proteus/proteus-1-5.xml
source/proteus/proteus-1-7.xml
source/proteus/proteus-1-8.xml
source/proteus/proteus-2-3.xml
source/proteus/proteus-2-5.xml
source/proteus/proteus-3-4.xml
source/proteus/proteus-3-5.xml
source/proteus/proteus-4-4.xml
source/proteus/proteus-template.xml

I changed all the places where I was doing
<p>
[PROTEUS exercises]
</p>
to
<title>PROTEUS exercises</title>

I should have been using <title>

---

project.ptx
source/proteus/proteus-3-2.xml

This says there are like five commits but I've checked that it only changes project.ptx.

un-re-order the project.ptx file
